# Generated by Django 3.1.2 on 2020-11-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetsVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('time', models.TimeField()),
                ('home_team', models.CharField(max_length=60)),
                ('away_team', models.CharField(max_length=60)),
                ('final_bet', models.CharField(max_length=1)),
                ('odds', models.FloatField()),
                ('amount', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('home_team', models.CharField(max_length=40)),
                ('away_team', models.CharField(max_length=40)),
                ('home_prob', models.IntegerField()),
                ('draw_prob', models.IntegerField()),
                ('away_prob', models.IntegerField()),
                ('bet_sign', models.CharField(max_length=1)),
                ('score_predict', models.CharField(max_length=10)),
                ('avg_goals', models.FloatField()),
                ('odds_for_prediction', models.FloatField()),
                ('home_odd', models.FloatField()),
                ('draw_odd', models.FloatField()),
                ('away_odd', models.FloatField()),
                ('temp', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RegularGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('home_team', models.CharField(max_length=40)),
                ('away_team', models.CharField(max_length=40)),
                ('score', models.CharField(default='-', max_length=7)),
                ('home_odd', models.FloatField()),
                ('draw_odd', models.FloatField()),
                ('away_odd', models.FloatField()),
                ('added_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('home_team', models.CharField(max_length=40)),
                ('away_team', models.CharField(max_length=40)),
                ('score', models.CharField(max_length=7)),
                ('home_odd', models.FloatField()),
                ('draw_odd', models.FloatField()),
                ('away_odd', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrendModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trend_1', models.CharField(blank=True, max_length=500, null=True)),
                ('trend_2', models.CharField(blank=True, max_length=500, null=True)),
                ('trend_3', models.CharField(blank=True, max_length=500, null=True)),
                ('trend_4', models.CharField(blank=True, max_length=500, null=True)),
                ('trend_5', models.CharField(blank=True, max_length=500, null=True)),
                ('trend_6', models.CharField(blank=True, max_length=500, null=True)),
                ('trend_7', models.CharField(blank=True, max_length=500, null=True)),
                ('trend_8', models.CharField(blank=True, max_length=500, null=True)),
                ('trend_9', models.CharField(blank=True, max_length=500, null=True)),
                ('trend_10', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValueBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('home_team', models.CharField(max_length=40)),
                ('away_team', models.CharField(max_length=40)),
                ('home_prob', models.IntegerField()),
                ('draw_prob', models.IntegerField()),
                ('away_prob', models.IntegerField()),
                ('bet_sign', models.CharField(max_length=1)),
                ('odds_for_pred', models.FloatField()),
                ('home_odd', models.FloatField()),
                ('draw_odd', models.FloatField()),
                ('away_odd', models.FloatField()),
                ('value_percent', models.IntegerField()),
            ],
        ),
    ]
