# Generated by Django 3.1.2 on 2020-10-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetsVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('time', models.TimeField()),
                ('home_team', models.CharField(max_length=60)),
                ('away_team', models.CharField(max_length=60)),
                ('final_bet', models.CharField(max_length=1)),
                ('odds', models.FloatField()),
                ('amount', models.CharField(max_length=30)),
            ],
        ),
    ]
