# Generated by Django 3.1.2 on 2020-10-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='bet_sign',
            field=models.CharField(max_length=1),
        ),
    ]
