# Generated by Django 3.1.2 on 2020-11-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
        migrations.RemoveField(
            model_name='regulargame',
            name='date',
        ),
    ]
