# Generated by Django 3.1.2 on 2020-10-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_auto_20201017_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueBets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('home_team', models.CharField(max_length=40)),
                ('away_team', models.CharField(max_length=40)),
                ('home_prob', models.IntegerField()),
                ('draw_prob', models.IntegerField()),
                ('away_prob', models.IntegerField()),
                ('bet_sign', models.CharField(max_length=1)),
                ('odds_for_pred', models.FloatField()),
                ('home_odd', models.FloatField()),
                ('draw_odd', models.FloatField()),
                ('away_odd', models.FloatField()),
                ('value_percent', models.IntegerField()),
            ],
        ),
    ]
