# Generated by Django 3.1.2 on 2020-10-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_valuebets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValueBets',
            new_name='ValueBet',
        ),
    ]
