# Generated by Django 3.1.2 on 2020-10-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_auto_20201018_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('home_team', models.CharField(max_length=40)),
                ('away_team', models.CharField(max_length=40)),
                ('home_odd', models.FloatField()),
                ('draw_odd', models.FloatField()),
                ('away_odd', models.FloatField()),
            ],
        ),
    ]
