# Generated by Django 3.1.2 on 2020-11-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_regulargame'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('home_team', models.CharField(max_length=40)),
                ('away_team', models.CharField(max_length=40)),
                ('score', models.CharField(max_length=7)),
                ('home_odd', models.FloatField()),
                ('draw_odd', models.FloatField()),
                ('away_odd', models.FloatField()),
            ],
        ),
    ]
