# Generated by Django 3.1.2 on 2020-11-18 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0008_regulargame_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulargame',
            name='added_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regulargame',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultgame',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
