# Generated by Django 3.1.2 on 2020-11-18 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0010_auto_20201118_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulargame',
            name='added_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
