# Generated by Django 3.1.2 on 2020-11-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0011_regulargame_added_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulargame',
            name='date',
            field=models.DateField(default=1991),
            preserve_default=False,
        ),
    ]
