# Generated by Django 3.1.2 on 2020-11-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0012_regulargame_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulargame',
            name='date',
        ),
        migrations.AddField(
            model_name='resultgame',
            name='date',
            field=models.DateField(default=1992),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regulargame',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
