# Generated by Django 3.1.2 on 2020-11-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0013_auto_20201118_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultgame',
            name='date',
        ),
        migrations.AddField(
            model_name='regulargame',
            name='date',
            field=models.DateField(default=1991),
            preserve_default=False,
        ),
    ]
