# Generated by Django 3.1.2 on 2020-11-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0014_auto_20201118_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulargame',
            name='time',
            field=models.TimeField(),
        ),
    ]
