# Generated by Django 3.1.2 on 2020-11-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0015_auto_20201118_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulargame',
            name='score',
        ),
    ]
