# Generated by Django 3.1.2 on 2020-11-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0017_auto_20201118_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('home_team', models.CharField(max_length=40)),
                ('away_team', models.CharField(max_length=40)),
                ('score', models.CharField(default='-', max_length=7)),
                ('home_odd', models.FloatField()),
                ('draw_odd', models.FloatField()),
                ('away_odd', models.FloatField()),
                ('added_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UpcomingGame',
        ),
    ]
