# Generated by Django 3.1.2 on 2020-11-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0010_regulargame_date'),
        ('traffic', '0018_auto_20201118_1111'),
    ]

    operations = [
    ]
